### PR TITLE
Bump kesytone chart

### PR DESCRIPTION
**Pull request by Itxaka**
Includes changes to probes to avoid probewarnings

### CODE REVIEW

**Comment by jsuchome** [comment]
Could you add a link the changes you mention  in commit message?

**Comment by Itxaka** [comment]
> Could you add a link the changes you mention in commit message?

Sorry I sent this yesterday nigth to check whether it would be working on the latest version or not, its just a test for the moment until I find out why its not working, as it may require more changes.

**Comment by jsuchome** [comment]
OK, thanks for explanation (but if you indeed find this is needed, include the link in the commit message :-) )

**Comment by Itxaka** [comment]
Closing this, will send a PR with this and other commits altogether as they are all small fixes for the same purpouse

**Pull request closed without merging**
