### PR TITLE
Allow keeping the CI machines after the run

### PR DESCRIPTION
**Pull request by Itxaka**
Allows to keep the instances up for 3 hours for troubleshooting them

### CODE REVIEW

**Comment by jsuchome** [comment]
If the option is set, it affects both failed and successful runs, right? That's what I think it should do.

**Comment by Itxaka** [comment]
unfortunately this did not work, checking out the params to see if there is something wrong here....

**Comment by Itxaka** [comment]
now its working, I was comparing a bool to a string....

**Comment by AbelNavarro** [comment]
I think this was asked before, but you'll need to pass that parameter when triggering the build to be effective. So you either set the CI to always keeps the jobs 3 hours or manually re-trigger a build with a request to keep it. What would be the approach here?

**Comment by Itxaka** [comment]
> I think this was asked before, but you'll need to pass that  parameter when triggering the build to be effective. So you either set  the CI to always keeps the jobs 3 hours or manually re-trigger a build  with a request to keep it. What would be the approach here?

So for now this is done on demand, by triggering a manual job with the option enabled.

In the future @jsuchome proposed having it check for a file so we can go into the jenkins instance and create that file for a running job, and it would keep it running.

In the future, if we get to a more stable green job, we could do this for failed instances only, but I think that approach is dangerous as any broken patch would block a lot of jobs.

**Comment by evrardjp** [comment]
I like the future approach of a tempfile in the PR too. It's simple. And a bot can automatically mark the PR as do not merge if it includes said file :)

**Pull request merged**
