### PR TITLE
Add argbash support for argparsing

### PR DESCRIPTION
**Pull request by hemna**
This PR adds argument parsing support via the argbash templating mechanism. 

It adds:
- [x] help generation
- [x] command 

Environment vars

- [x] DEPLOYMENT_MECHANISM 
- [x] SOCOK8S_DEVELOPER_MODE
- [x] USE_ARA

```
 ./run.sh -h
This script is used to bootstrap the socok8s dev env. To build the documentation, run tox -edocs
Usage: ./run.sh [-q|--(no-)quiet] [-h|--help] [<command>]
	<command>: The command you want to run. (default: 'setup_everything')
	-q, --quiet, --no-quiet: suppress noisy output (off by default)
	-h, --help: Prints help

Environment variables that are supported:
	DEPLOYMENT_MECHANISM: The deployment type you want. (default: 'openstack')
	SOCOK8S_DEVELOPER_MODE: Enable SOCOK8S script developer mode. (default: 'False')
	USE_ARA: Use ARA?. (default: 'False')
```

### CODE REVIEW

**Comment by hemna** [comment]
I can't see why the  suse-cloud/socok8s job is failing.  The details link never comes up.

**Comment by jsuchome** [comment]
I think it's not correctly set up yet

**Comment by hemna** [comment]
ok looks like the CI job is failing due to a missing INTERNAL_NETWORK not being defined.  Looks like all of the PR's are failing for the same reason too.

**Comment by hemna** [comment]
abandoning

**Pull request closed without merging**
