### PR TITLE
Fix the variable name containing loci build command.

### PR DESCRIPTION
**Pull request by jsuchome**
Also, stay on ocata for now.

### CODE REVIEW

**Comment by jsuchome** [comment]
> Also, stay on ocata for now.

Well, that might not be good idea, building for ocata seems to fail, I'll remove this part of the commit

**Comment by evrardjp** [comment]
yeah but master fails too :p 
Should we move to queens?

**Comment by jsuchome** [comment]
Current script does point to queens

**Comment by evrardjp** [comment]
We should probably build the wrapper for rocky in upstream too, and move to it. But it's a little premature, as Queens is not working yet in upstream...

**Pull request merged**
