### PR TITLE
Run tempest test in serial mode

### PR DESCRIPTION
**Pull request by AbelNavarro**

### CODE REVIEW

**Comment by jsuchome** [comment]
Did you try more than one run to ensure this is not just a chance?

**Comment by AbelNavarro** [comment]
> Did you try more than one run to ensure this is not just a chance?

nope, will run it locally to test that.

**Comment by Itxaka** [comment]
lets retrigger the CI job as well

**Comment by AbelNavarro** [comment]
There have been 3 failed rebuilds on this PR. The problems seem to be unrelated to the change:
- Invalid repository
- Failure on terraform apply
- time out while deploying kube-system-ingress

I tried locally as well. Several tests were failing, only one with 503 error, but also several failing due to timeouts trying to reach `compute.openstack.svc.cluster.local` which I think it's related to those 503s.

So, this is an improvement over the previous situation but it doesn't solve all problems.

**Pull request closed without merging**
