### PR TITLE
Restore caasp automation from kubic-project

### PR DESCRIPTION
**Pull request by Itxaka**
It seems that the repo has gone missing so restore the files while we
look for a replacement

### CODE REVIEW

**Comment by jsuchome** [comment]
+1 until we find out what's wrong ... does anyone know where to ask?

**Comment by Itxaka** [comment]
I asked on the #kubic room in freenode, everything seems to point there as a contact point

**Comment by Itxaka** [comment]
oh my, we also need to copy the `velum-interactions` tool :crying_cat_face:

**Comment by evrardjp** [comment]
That behaviour is very bad. I am kinda disappointed nobody checked on us before completely deleting (vs archiving).

**Comment by Itxaka** [comment]
from the #kubic chat:

`<fvogt> itxaka: It was removed because it wasn't used by and for kubic - you should ask about that internally`

so we may need to escalate this internally with the kubic team :)

**Comment by evrardjp** [comment]
I think it's fair, I just hoped they would "redirect" or "change ownership" vs deleting it.

**Comment by jsuchome** [comment]
Do they guarantee the functionality, so we can assume it works if we have it in our own repo?

**Comment by Itxaka** [comment]
This seems to be ready for review, I tested the modified step `enroll_caasp_workers` and it works as it did before.

Currently testing `deploy_caasp`

**Comment by Itxaka** [comment]
deploy_caasp also run correctly

**Pull request merged**
