### PR TITLE
Increase worker counts


### PR DESCRIPTION
**Pull request by evrardjp**
Decrease load on master, which will help us in the long run

### CODE REVIEW

**Comment by evrardjp** [comment]
@jsuchome Not sure about that. It should be automatically done, what's the code you are thinking about?

**Comment by jsuchome** [comment]
Hm, I was thinking `environment.json` but you are right, that should be generated

**Comment by evrardjp** [comment]
This changes the defaults, but ansible is passing that as a variable anyway, so I am not 100% sure it's really needed.

**Comment by Itxaka** [comment]
needs rebase!

**Comment by evrardjp** [comment]
We can probably abandon this, now this parameter is given to the stack.
https://github.com/SUSE-Cloud/socok8s/blob/2875bdce944f5e1b730affd6baeedddb87475fdd/playbooks/openstack-deploy_caasp.yml#L47

**Pull request closed without merging**
