### PR TITLE
CI: Switch SES deployment to rook

### PR DESCRIPTION
**Pull request by jsuchome**
We should wait at least for https://github.com/SUSE-Cloud/socok8s/pull/730

This is only the CI, no code cleanup yet

### CODE REVIEW

**Comment by Itxaka** [comment]
just rebased to include the better flavors, lets see if we don not hit a 503 this time

**Comment by Itxaka** [comment]
Green to deploy but a lot of tempest failures with error 503, we need to check the pod logs to see if something went wrong or what.

**Comment by jhesketh** [comment]
The west squad also made a good point that we want to make sure SES6 is working well for the KVM type deployment before completely removing SES5.

**Comment by jsuchome** [comment]
@jhesketh Good point but it actually is related to https://github.com/SUSE-Cloud/socok8s/pull/733 which removes the code path to deploy SES5. 
This PR only changes what is done in CI which does not affect KVM users anyway.

**Comment by Itxaka** [comment]
job retriggered to check if its a consistent failure

**Comment by jsuchome** [comment]
(I still believe this one could be merged, as it affects only CI, and still keeps non-rook deployment path. Assuming it passes of course)

**Comment by evrardjp** [comment]
Love to idea, sad that it's red in Jenkins.

**Comment by jsuchome** [comment]
We need https://github.com/SUSE-Cloud/socok8s/pull/735 before, registry.suse.de does not seem to contain right images.

**Pull request closed without merging**
