### PR TITLE
Remove SUSE-cloud/automation module

### PR DESCRIPTION
**Pull request by rajdharwadkar**
Removing SUSE-cloud/automation module because it is not used.

### CODE REVIEW

**Comment by jsuchome** [comment]
So, why we needed it in the first place? Because of CaaSP3? (It would be great to mention the reason for removal in the commit message)

**Comment by jhesketh** [comment]
It's no longer needed/used afaik, but yes, mentioning that in the commit message would be helpful.

**Comment by rajdharwadkar** [comment]
> So, why we needed it in the first place? Because of CaaSP3? (It would be great to mention the reason for removal in the commit message)

I am not sure why and when this was added.

**Comment by rajdharwadkar** [comment]
> You need to remove the automation from the .gitmodules, otherwise it would fail: https://github.com/SUSE-Cloud/socok8s/blob/master/.gitmodules

yes thanks . Fixed.

**Comment by rajdharwadkar** [comment]
We need these changes to go in first : 
https://github.com/SUSE-Cloud/socok8s/pull/731/files
https://github.com/SUSE-Cloud/socok8s/pull/733/files

**Pull request closed without merging**
