### PR TITLE
Remove PREFIX variable


### PR DESCRIPTION
**Pull request by evrardjp**
Some vars are derived from PREFIX, some are not. This simplifies
by making everything explicit. It removes PREFIX from the code
requirements.

### CODE REVIEW

**Comment by evrardjp** [comment]
This requires:
1) A change in SUSE-Cloud/automation
2) The change in the heat stack #232 .
3) A rebase when #230 will merge.

**Comment by toabctl** [comment]
As discussed on mumble, I would prefer to use the `PREFIX` variable everywhere to define the needed resources (like network, servers, volumes, ...)

**Comment by evrardjp** [comment]
We'll also need to define keypair by prefix.

I believe this PR should be revised with the input given in our meeting https://github.com/SUSE-Cloud/socok8s/pull/230#issuecomment-480739616 .

I will go back to the drawing board, giving the variable a different name than "PREFIX" (like suggested in the meeting: environment_name or something)

**Comment by evrardjp** [comment]
Abandonning this.

**Pull request closed without merging**
