### PR TITLE
Remove the code for standalone SES node

### PR DESCRIPTION
**Pull request by jsuchome**
~WIP: there's still some code using common-ses role where it should not be needed~

### CODE REVIEW

**Comment by Itxaka** [comment]
type: standalon*e*

**Comment by Itxaka** [comment]
do we want to rewrite ses-rook to be ses6?

**Comment by jsuchome** [comment]
> airship+tempest run correctly, 4 tests failed as usual, looks good to me

i'm surprised. Any idea why it was failing previously?

**Comment by jsuchome** [comment]
@rajdharwadkar Thanks, updated!

**Comment by jsuchome** [comment]
TODO: remove also `deploy_on_openstack_ses_repos_per_imagename:` and relevant code

**Pull request closed without merging**
