### PR TITLE
Move caasp stack deletion to extra file

### PR DESCRIPTION
**Pull request by toabctl**
Instead of using a "when" statement, just run the deploy or cleanup
playbook during the deployment or teardown step.

### CODE REVIEW

**Comment by jsuchome** [comment]
What about renaming the original playbook to  openstack-create-caasp?
Or at least have both of them named in the same style, like "prepare-caasp"/"cleanup-caasp" or "create-caasp-instance"/"delete-caasp-instance" ?

**Comment by evrardjp** [comment]
> What about renaming the original playbook to openstack-create-caasp?
> Or at least have both of them named in the same style, like "prepare-caasp"/"cleanup-caasp" or "create-caasp-instance"/"delete-caasp-instance" ?

I guess we could do that for consistency. openstack-create_caasp and openstack-delete_caasp make sense to me.

**Comment by toabctl** [comment]
@

> What about renaming the original playbook to openstack-create-caasp?
> Or at least have both of them named in the same style, like "prepare-caasp"/"cleanup-caasp" or "create-caasp-instance"/"delete-caasp-instance" ?

@jsuchome can that be done in a follow up commit (so I can rename also the network deploy playbook) ?

**Comment by toabctl** [comment]
> What about renaming the original playbook to openstack-create-caasp?
> Or at least have both of them named in the same style, like "prepare-caasp"/"cleanup-caasp" or "create-caasp-instance"/"delete-caasp-instance" ?

@jsuchome done in https://github.com/SUSE-Cloud/socok8s/pull/295

**Pull request merged**
