### PR TITLE
Use CaaSP 3.0.0 image with latest updates

### PR DESCRIPTION
**Pull request by jsuchome**
An alternative to https://github.com/SUSE-Cloud/socok8s/pull/164

### CODE REVIEW

**Comment by jsuchome** [comment]
@evrardjp sorry, but where in the deployment guide are we currently sharing that information?

**Comment by evrardjp** [comment]
We are currently not doing it, because we said "deploy caasp". Now that we have more requirements, we should express them in docs. https://github.com/SUSE-Cloud/socok8s/blob/master/doc/source/deploy-guide/prepare-targets.rst would be a good place.

**Comment by Itxaka** [comment]
@jsuchome close this? or do we want to still investigate this path?

**Comment by jsuchome** [comment]
Closing, at least for now

**Pull request closed without merging**
