### PR TITLE
Remove cloud variable


### PR DESCRIPTION
**Pull request by evrardjp**
There is no need to expose `cloud`, as we are expecting the
developer to set OS_CLOUD in run.sh, and all those plays are
working on localhost.

### CODE REVIEW

**Comment by evrardjp** [comment]
Only merge this when the first two commits are merged in PR #230 .

**Comment by evrardjp** [comment]
This can be done in the reimplementation of #230.

**Comment by evrardjp** [comment]
This was tested and working in my environment.

**Comment by toabctl** [comment]
@evrardjp is this still needed?

**Comment by evrardjp** [comment]
> @evrardjp is this still needed?

Needed no, useful yes. Will re-create a new one, because I am not into conflict resolution mode.

**Pull request closed without merging**
