### PR TITLE
Freeze helm repositories to the same version that is used by airship (do not merge)

### PR DESCRIPTION
**Pull request by jsuchome**
Updating helm repo's references to the ones present in 

https://github.com/SUSE-Cloud/socok8s/blob/master/site/soc/software/config/versions.yaml

### CODE REVIEW

**Comment by jsuchome** [comment]
Let's solve the way of applying patches elsewhere

**Comment by jgu17** [comment]
A good start to get general alignment! Airship supports individual version/tag for each service, I don't think we'll need to do that for the osh development purpose, at least not yet.

**Comment by jsuchome** [comment]
@jgu17 well, that means this change does _not_ affect airship, right? And as it is not needed for OSH, I agree with @evrardjp that this is unnecessary after all

**Comment by jgu17** [comment]
> @jgu17 well, that means this change does not affect airship, right? And as it is not needed for OSH, I agree with @evrardjp that this is unnecessary after all

No this patch doesn't affect Airship at all. I thought you wanted to control osh side.

**Comment by jsuchome** [comment]
Not needed for OSH development

**Pull request closed without merging**
