### PR TITLE
New patches for dev-patcher; removed the merged ones

### PR DESCRIPTION
**Pull request by jsuchome**
Also, bump a version for loci and osh-images repos

### CODE REVIEW

**Comment by evrardjp** [comment]
We said no merge for today though.

**Comment by evrardjp** [comment]
Can you rebase?

**Comment by jsuchome** [comment]
Rebased - I also removed frozen versions of upstream repos, that might be problematic I know

**Comment by evrardjp** [comment]
@matthew-fuller probably worth having a look at this, it might interest you.

**Pull request merged**
