### PR TITLE
Use Leap 15 for OSH deployer node

### PR DESCRIPTION
**Pull request by evrardjp**
This adds the repository necessary for ruby installation
(devel:tools) and adds the necessary minimum software for the velum-tooling
in the packages to install.

### CODE REVIEW

**Comment by jsuchome** [comment]
Please change the PR title (it's not just about 2nd commit)

**Comment by Itxaka** [comment]
agh, merge conflicts :(

**Comment by evrardjp** [comment]
I am finishing my WIP patch then solve this. Probably time to do something else in european timezones though ;p

**Comment by evrardjp** [comment]
Fixed.

**Pull request merged**
