### PR TITLE
Caasp4 episode 3: Revenge of the caasp

### PR DESCRIPTION
**Pull request by Itxaka**
CAASP! The Republic is crumbling
under attacks by the ruthless
Sith Lord, Count Dooku.
There are heroes on both sides.
Evil is everywhere.

In a stunning move, the
fiendish droid leader, General
Grievous, has swept into the
Republic capital and kidnapped
Chancellor Palpatine, leader of
the Galactic Senate.

As the Separatist Droid Army
attempts to flee the besieged
capital with their valuable
hostage, two Jedi Knights lead a
desperate mission to rescue the
captive Chancellor....

### CODE REVIEW

**Comment by Itxaka** [comment]
Technically it finished correctly, but there are 2 steps that should be skipped (docker restart)

```
[2019-08-14T17:55:26.380Z]     step/01DJ8F8EBC9RNZ7FRB0F55M73J/action_xcom                          1            success
[2019-08-14T17:55:26.380Z]     step/01DJ8F8EBC9RNZ7FRB0F55M73J/dag_concurrency_check                2            success
[2019-08-14T17:55:26.380Z]     step/01DJ8F8EBC9RNZ7FRB0F55M73J/deployment_configuration             3            success
[2019-08-14T17:55:26.380Z]     step/01DJ8F8EBC9RNZ7FRB0F55M73J/validate_site_design                 4            success
[2019-08-14T17:55:26.380Z]     step/01DJ8F8EBC9RNZ7FRB0F55M73J/armada_build                         5            success
[2019-08-14T17:55:26.380Z]     step/01DJ8F8EBC9RNZ7FRB0F55M73J/decide_airflow_upgrade               6            success
[2019-08-14T17:55:26.380Z]     step/01DJ8F8EBC9RNZ7FRB0F55M73J/armada_get_status                    7            success
[2019-08-14T17:55:26.380Z]     step/01DJ8F8EBC9RNZ7FRB0F55M73J/upgrade_airflow                      8            skipped
[2019-08-14T17:55:26.380Z]     step/01DJ8F8EBC9RNZ7FRB0F55M73J/skip_upgrade_airflow                 9            success
[2019-08-14T17:55:26.380Z]     step/01DJ8F8EBC9RNZ7FRB0F55M73J/armada_post_apply                    10           success
[2019-08-14T17:55:26.380Z]     step/01DJ8F8EBC9RNZ7FRB0F55M73J/create_action_tag                    11           success
[2019-08-14T17:55:26.380Z]     step/01DJ8F8EBC9RNZ7FRB0F55M73J/deployment_status                    12           success
[2019-08-14T17:55:26.380Z]     step/01DJ8F8EBC9RNZ7FRB0F55M73J/deckhand_validate_site_design        13           success
[2019-08-14T17:55:26.380Z]     step/01DJ8F8EBC9RNZ7FRB0F55M73J/armada_validate_site_design          14           success
[2019-08-14T17:55:26.380Z]     step/01DJ8F8EBC9RNZ7FRB0F55M73J/armada_get_releases                  15           success
[2019-08-14T17:55:26.380Z]     step/01DJ8F8EBC9RNZ7FRB0F55M73J/final_deployment_status              16           success
[2019-08-14T17:55:26.380Z]   
[2019-08-14T17:55:26.380Z]   
[2019-08-14T17:55:26.380Z]   
[2019-08-14T17:55:26.380Z]     Commands        User            Datetime
[2019-08-14T17:55:26.380Z]     invoke          shipyard        2019-08-14 16:27:10.867668+00:00
```

**Comment by jsuchome** [comment]
I'm testing this locally with `deploy_osh`. It keeps failing when helm is running keystone test pod:
```
# helm test keystone --timeout 900
RUNNING: keystone-test
E0815 07:31:55.618486   25047 portforward.go:224] lost connection to pod
Error: transport is closing
```
From kubectl logs tiller-deploy:

```
[storage] 2019/08/15 07:31:05 getting last revision of "keystone"
[storage] 2019/08/15 07:31:05 getting release history for "keystone"
[tiller] 2019/08/15 07:31:05 running tests for release keystone
[kube] 2019/08/15 07:31:05 building resources from manifest
[kube] 2019/08/15 07:31:05 creating 1 resource(s)
[kube] 2019/08/15 07:31:06 Watching pod keystone-test for completion with timeout of 15m0s
[tiller] 2019/08/15 07:36:27 error running test suite for keystone: rpc error: code = Unavailable desc = transport is closing
```

**Comment by jsuchome** [comment]
OK, good news is that local airship deployment works for me, just like in the CI.

Bad news is, I can see the same behavior with the tests:
```# helm test airship-keystone --timeout 900
RUNNING: airship-keystone-test
E0815 13:39:42.312757   17290 portforward.go:224] lost connection to pod
Error: transport is closing```

I guess airship does not check the result of helm executing the test, that might be why we do not see it in CI

**Comment by Itxaka** [comment]
Caasp4 test run here: https://ci.suse.de/blue/organizations/jenkins/cloud-socok8s-jobs%2Fsocok8s-integration/detail/PR-674/14/pipeline

**Comment by Itxaka** [comment]
Reached port quota on CI will wait a bit before retriggering the caasp3 job

**Pull request merged**
